name: Flutter Linux Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.32.4

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev libstdc++-12-dev

      - name: Run build for linux
        run: flutter build linux --release
        env:
          FLUTTER_BUILD_MODE: release

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Release-${{ github.run_number }}
          files: build/linux/x64/release/bundle/**/*
