name: Flutter Linux Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.8.1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run build for linux
        run: flutter build linux --release
        env:
          FLUTTER_BUILD_MODE: release

      # Zip the build output and upload it to the release
      - name: Zip build output
        run: zip -r nasa_apod_x64.zip build/linux/x64/release/bundle

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: nasa_apod_x64.zip

